### ISSUE TITLE
Fix that the timer keeps running after deleting the current timeframe

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#102]
For some reason, I tried deleting the current timeframe – the one with the active timer. It could be deleted without problems, but the timer was still shown as running (red dots in the project tree, and the "red square" icon to stop it in the toolbar). And now when pressing the "red square" icon in the toolbar, nothing happens, the timer is shown as still running.

Probably you want to automatically stop a running timer before deleting the timeframe to which it belongs.

**Comment by jansorg** [comment]
The timer is stopped, the display is not. You can safely restart to workaround this.
Should be fixed at some point...

**Comment by jansorg** [comment]
Should be fixed with the next update
