### ISSUE TITLE
Use Esc for stopping a timer

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#103]
I just found myself hitting <kbd>Esc</kbd> to try stopping a running timer. And now I think that could be a better (simpler and more intuitive) option than the current <kbd>Shift</kbd> + <kbd>Space</kbd>, while also preserving the option to start a _new_ timer at any time with just <kbd>Space</kbd>.

**Comment by jansorg** [comment]
The next update will have better defaults and configurable shortcuts for both application and global shortcuts.
