### ISSUE TITLE
Reporting: Render linebreaks in the description field

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#104]
When creating a new report, there is a field that says "Your description to display at the top of the report…".

This field allows to enter line breaks, but in the output everything will be placed into a single line. Would help to have line breaks here, as well. (Oh and Markdown formatting in that field. But not really.)

**Comment by jansorg** [comment]
@tanius Hm, html should be accepted here. I'm not 100% sure atm, though.

**Comment by jansorg** [comment]
HTML wasn't allowed.
It will be allowed with the next update. Use `<br>` to insert a line break.
