### ISSUE TITLE
Reporting: Don't append " project" to project names

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#105]
When enabling "Splitting: Project" in the report creation window, project titles will appear as headers over individual tables, rendered in blue. At their end, the string "` project`" is appended, rendered in the same font. Depending on how the project is named, this addition can be confusing.

Proposal: Either just omit the "` project`" string completely, or prepend it as "`Project: `", rendered in the same font but in light gray.

**Comment by jansorg** [comment]
Fixes for the next update
