### ISSUE TITLE
Reporting: Support different date formats in "Time range:"

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#106]
When enabling "Template: Show summary" in the report creation window, a small table will appear at the start of the report that shows the time range the report is about.

This is always using the U.S. American date format for now. Would be great to make this configurable. Probably Qt has support for configurable regional settings for date, time and number formats?

**Comment by jansorg** [comment]
@tanius `tom` is supporting English and German, `tom-ui` only uses the current environment which is then passed to `tom`.
As a workaround, you could try if `LANG=de_DE LC_ALL=de_DE.UTF8 tom-ui` is showing the expected results.
A good fix for this is probably to show a language dropdown in the report configuration.

**Comment by jansorg** [comment]
Should be fixed by 0.12

**Comment by tanius** [comment]
> As a workaround, you could try if LANG=de_DE LC_ALL=de_DE.UTF8 tom-ui is showing the expected results.

Indeed this works to influence the date format used in reports. (Only testing it now in tom-ui 0.12 though.)

And thanks for the ISO dates option!
