### ISSUE TITLE
Clarify how rounding works

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#109]
When creating a report, there is a setting "Time entries → Round entries".

Now in `tom-ui`, "time entries" refers to the start/stop records of a (sub-)project, as can be seen from the main menu item "Time Entries". The "Time entries → Round entries" setting however does not round individual time entries, so the current wording is confusing. Instead, rounding currently affects the per-day sub-totals of each sub-project.

**Proposed solution.** I propose a somewhat larger re-ordering of the options on the "Reports → Create project report …" screen. (Here I just propose the logical hierarchy of form entries, which can then be expressed with form elements in various ways.)

* **Title** (as currently)
* **Description** (as currently)
* **Data selection**
    * **Project**
    * **Filter by date**
    * **Include archived entries**
* **Processing**
    * **Round daily worktimes per (sub-)project**
* **Display**
    * **Split by**
    * **Template**
    * **Template options** (would include all checkboxes below the "default / timelog" dropdown and allow to show different entries here depending on the template chosen)

Maybe in the future it makes sense to make it configurable what the rounding is applied to. Options could be time entries, daily / weekly / monthly / yearly worktimes per project etc., or could depend on the splitting. But probably that's just making things too complicated, esp. in combination with the multiple templates and splitting options.

**Comment by jansorg** [comment]
@tanius I'd need to take a closer look, but as far as I remember:
- rounding is applied to the time entries iteself which is then reflected in the durations on the lowest level (i.e. days if split by days)
- I agree that the wording is a bit confusing here
- Rounding can become very complex. Rounding start and/or end times would be possible, but this will create mismatches with the durations.
- Offering "snapping" start and end time to full seconds or minutes (start to previous, end to next) might be useful, but that's equivalent to rounding up and down to full minutes. The resulting times could then be rounded. But I'm not sure if there's a client who understands what's going on in such a case :)

**Comment by tanius** [comment]
> The "Time entries → Round entries" setting however does not round individual time entries

With the changes in #108, rounding is applied to the individual time entries now, and the confusion that resulted from the previous situation is gone now. I think we can close this as duplicate and deal with remaining ways to improve rounding in #108.
