### ISSUE TITLE
Fix that time entry start times are often off by + or - 2 hours in reports

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#110]
When I create a report and choose the "timelog" template for it, there will be tables showing the actual time entries of when I worked. The time entry _durations_ derived from time entries are correct, however about half of the start times are displayed with an offset of either plus or minus two hours compared to the real time entries as seen outside of the report window.

So there is a display issue with the start times of time entries. I could not find a system in the erroneous offsets, but perhaps it has something to do with time zones?

To me, this issue happens independent of whatever other options I choose in the report generation dialog, including what type of splitting is chosen.

**Comment by jansorg** [comment]
@tanius There's some internal timezone  conversion happening to convert from the internal UTC storage (I think) to the local timezone. This is probably missing somewhere.

**Comment by jansorg** [comment]
Let me know if you have an example, where this happens

**Comment by tanius** [comment]
Here is an example as it appears in my report using timelog entries. I have added the correct times from the timeframes list in red to any time that is off.

As you can see, it is quite random when it happens, and can affect start time, end time or both. One of the four entries was correct, the others had at least one issue. When only start time _or_ end time is affected, the shown duration does not represent the actual duration between start and end time, obviously. It can even happen that end time is before start time if only the end time is affected.

![Issue110 Example](https://user-images.githubusercontent.com/843907/179770703-c22d3a54-19da-4988-b7d9-9c874e21a2d1.png)

**Comment by jansorg** [comment]
Should be fixed for the next update. This is only a display issue, is perfectly valid for the stored data to contain different time zones.
