### ISSUE TITLE
Disable editing time entries when multiple ones are selected

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#114]
When right-clicking on a time entry in the list in the lower part of the program's window, a context menu will appear with a menu item "Edit frame…" (resp. "Edit time entry…", see #113).

That also happens when multiple time entries are selected. However, when multiple ones are selected the expectation is generally that any action will be about the whole selection. So the user does not really know which time entry will be affected: all? the first? the one under the pointer?

To me it would be clearer when this menu item is disabled (grayed out) when a multi-selection is active.

**Comment by jansorg** [comment]
Fixed for the next update
