### ISSUE TITLE
Provide tooltips for the "Subproject" column in the time entries list

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#122]
When a project is selected that has one or more levels of sub-projects, the time entries list contains an additional column "Subproject". At least with more than one level of sub-projects, this column can however never be wide enough to show the full value. To still make it useful, you could:

1. Provide a multiline tooltip overlay when mousing over a field value.

2. Place the "..." ellipsis for abbreviating content at the beginning of the field instead of its end. That will render the leaf-level sub-project name, which is the most specific and most useful bit of the full sub-project path to know. Even better, if possible you could render two ellipses: one to omit the part of the sub-project path up to the start of the leaf-level sub-project name, and if necessary another one for the end of that leaf-level sub-project name if it does not fit into the column otherwise.

**Comment by jansorg** [comment]
Fixed for the next update

**Comment by tanius** [comment]
This was actually a duplicate of #97.
