### ISSUE TITLE
Fix that sorting entries by end time lists the current entry at the wrong end

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#131]
In a list of time tracking entries that includes a currently active entry (that is, one without an end time), sorting by end time will show  this entry before the oldest entry in the list and not after the most recent entry as one would expect. The expectation comes from the fact that the end time can only be later than the current wall clock time, given that this entry is currently tracking time and, if stopped, would use the current wall clock time as its end time.

**Comment by jansorg** [comment]
Fixed for the next update
