### ISSUE TITLE
Taskbar icon turns inactive but timer is still active

### ISSUE THREAD

**Issue by damingo** [jansorg/tom-ui#28]
The taskbar icon changes back to the white "T" after some time, but the timer is still active. In the dropdown "Stop active project..." is disabled, but the red square is still displayed next to the active project in the dropdown-menu.

**Comment by damingo** [comment]
After this happened again (the icon in the taskbar turns inactive, the timer still running) it was not possible to stop the timer with the controls in he main window. After quitting tom-ui with Ctrl+Q and reopening it, the timer was still active and it was not possible to stop the timer with the buttons in the main window. However, it was possible to stop the timer with the "Stop active project..." action in the taskbar menu. The program was open for several days, the timer active for apprx. 30 mins.

**Comment by jansorg** [comment]
Wasn't able to reproduce. Please reopen when this happens again with the next update.
