### ISSUE TITLE
Reporting: make window suitable for smaller screens

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#43]
This is tom-ui 0.5.0 on Ubuntu 18.10.

The initial "Reports → Create project report …" screen will show in a size of 1143×1096 px, which is probably larger than many screens (1280×800 px here).

The window can be resized, but there's something about the layout managers (or how that is called in Qt) so that some form elements on the left side become invisible. See the attached screenshot – the form elements below "round entries" and "filter by date" are hidden or half hidden. Maybe just show a scrollbar for the whole left column of form elements when running out of screen space there?

![screenshot reportingwindowlayoutissues](https://user-images.githubusercontent.com/843907/52525801-46309a00-2caf-11e9-9c49-4da02d6c08fe.png)

**Comment by jansorg** [comment]
The next version adds scrollbars to the left group of settings
