### ISSUE TITLE
Left-click on status bar icon does nothing

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#44]
Currently, left-clicking the "black square" (no active timer) or "red square" (active timer) status bar icon does nothing. Right-clicking brings up the menu.

Idea: When the "red square" icon is shown, stop the timer when left-clicking on it. That seems to be the most intuitive thing to do, as clicking on a red square means "stop". Also, one would not have to do two right clicks to do the same like right now.

tom-ui 0.5.0 on Ubuntu 18.10 here.

**Comment by jansorg** [comment]
It now opens the main window. That's probably not working with virtual desktops.
Start/stop is better done via global shortcuts.
