### ISSUE TITLE
Allow to choose where to save a report

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#46]
When going to "Reports → Create project report …", right-clicking on the report and choosing "Save page", the report will be saved to a newly created `tom-report.[ID]" directory in the user's home directory. Users  won't know that and have to look it up in the manual, discover it by chance, or assume the feature is broken :-)

Proposal: Make it "Save page as …" and let users choose where to save. Initialize that dialog with a filename like `tom-report.2019-02-08-T-210613.html` (using the ISO 8601 date and time format in a variant suitable for filenames). Creating a directory is probably not needed, as small images etc. could be embedded into the HTML file using base64 encoding.

**Comment by jansorg** [comment]
The next update will have a separate "Save" button to save the file. The context menu is Qt's default and not working as shown and is now disabled.
