### ISSUE TITLE
When showing the window, show the current timeframe

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#59]
When using the "Show window" function from the context menu of the taskbar icon, it will currently show up with the (sub-)project selected that was selected last time when using the window. This way, it takes a bit of orientation to find the current timeframe (if there is one): look for the project with the red dot, click it, look at the first timeframe from the list that appears).

Since looking at / doing something with the current timeframe is what most users will do when showing the window, it could be a good idea to already select the corresponding project already in that case.

**Comment by jansorg** [comment]
Done for the next update
