### ISSUE TITLE
tom-ui 0.6.0 does not read its own project.json

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#60]
I installed latest `tom` and then `tom-ui` 0.6.0 using the provided `.deb` package. Started the software and created three projects A, B, C. They were showing alright. Then exited the software. At this point, `~/.tom/projects.json` had the following content:

    [{"id":"cf63a24d-32b4-4cc3-86e7-0daaefa01930","parent":"","name":"A"},{"id":"e60063b1-6981-4a6c-9549-db6296a0115b","parent":"","name":"B"},{"id":"51eb6f40-23d8-4aa6-b8d0-35deea9ba9f0","parent":"","name":"C"}]

When starting `tom-ui` again now, it would not show any project however, only the "All Projects" line as when starting it the very first time. Interestingly, projects I add now will be _added_ to `projects.json` without deleting the records already in there. But when restarting `tom-ui`, always no projects will show.

`tom` itself does not seem to have an issue. For example, `tom report` will list the projects A, B, C alright.

**Workaround:** Revert back to `tom-ui` 0.5.0. It will also list the projects created under `tom-ui` 0.6.0, which indicates that there's nothing wrong with the projects.json file created by `tom-ui` 0.6.0.

**Comment by jansorg** [comment]
Hm, that sound like that tom and tom-ui are not of the same version. Perhaps the build is messed up. I'll test the next release.

**Comment by tanius** [comment]
Probably this happened because I had `tom` installed via `go get github.com/jansorg/tom` in parallel to the `tom` contained in `tom-ui` 0.6.0, so it may have accessed the wrong `tom`. Wasn't clear to me that the `tom-ui` package now includes `tom` as well.

Anyway, it's working fine with `tom-ui` 0.7.3 now (and installing any `tom` before installing that).
