### ISSUE TITLE
tom from tom-0.7.3-ubuntu-18.10.deb misses "executable" permission

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#63]
When installing `tom-ui` from package `tom-0.7.3-ubuntu-18.10.deb` (from [here](https://github.com/jansorg/tom-ui/releases)), it also installs an included version of `tom`. However the command `which tom` does not find any `tom` yet because:

    $ ls -l /usr/bin/tom
    -rw-r--r-- 1 root root 13668747 Mär  9 19:33 /usr/bin/tom

Workaround for now:

    sudo chmod a+x /usr/bin/tom

**Comment by jansorg** [comment]
The next version will not ship tom withing tom-ui. The separate package should be used for that.
