### ISSUE TITLE
Name release files "tom-ui_[…].deb"

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#64]
Currently, both the [releases of tom](https://github.com/jansorg/tom/releases) and the [releases of tom-ui](https://github.com/jansorg/tom-ui/releases) have basically the same filenames. For example:

    tom:    tom_0.7.3_Linux-64-bit.deb
    tom-ui: tom-0.7.3-ubuntu-18.10.deb

It would be less confusing to name the `tom-ui` package `tom-ui-0.7.3-ubuntu-18.10.deb`, even though it also includes tom (which can be included in the documentation).

Using the [Debian convention for package filenames](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-pkgname), the names would probably be:

    tom:    tom_0.7.3_amd64.deb
    tom-ui: tom-ui_0.7.3-ubuntu18.10_amd64.deb

**Comment by jansorg** [comment]
Should be fixed for the next update.
The `tom-ui` package will no longer include the `tom` binary but will have a dependency on the `tom` package. The `tom` package has additional configuration, e.g. for commandline autocompletion, which I don't want to replicate for the tom-ui package setup.
