### ISSUE TITLE
Show icon for "archived entry" immediately after archiving

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#65]
With "Settings → Show archived entries" checked, right-click on a timeframe in the list and choose "Archive". This does not yet change anything visually, but after unchecking and re-checking the "Settings → Show archived entries" the timeframe is shown with the icon indicating "archived".

That icon is probably meant to be shown right away when archiving timeframes.

`tom-ui` 0.7.3 here.

**Comment by jansorg** [comment]
Done for next update
