### ISSUE TITLE
Use "Space" key to start and stop a timer

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#66]
Not too sure about this, but: since the <kbd>Space</kbd> bar key is not needed right now in the project tree and timeframes list, it could be a convenient keybinding for both starting and stopping the timers. Especially in combination with the current style of navigating the project tree using up and down arrows (for moving up / down) and left and right arrows (for folding / unfolding an entry).

So:

* When a project with an active timer is selected, <kbd>Space</kbd> would stop that timer.
* When a project without an active timer is selected, <kbd>Space</kbd> would stop any active timer or another project (if any) and then start a timer for the selected project. Which is what "Project → Start timer" does right now.

**Comment by jansorg** [comment]
I'd like to keep the feature that "Start timer" on a project with the active timer stops the current and then creates a new entry. This might be useful to start a new task on the same project.

The next update has :
- <kbd>space<kbd> to start a new timer on the currently selected project
- <kbd>shift + space<kbd> to stop the currently active timer
