### ISSUE TITLE
Update UI when adding an end time to the current time entry

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#71]
When editing the end time of the currently active timeframe, this will stop a running timer – makes sense, as the end time is now no longer unset but a fixed value.

However, the user interface does not yet reflect such a change. What's missing:

* Remove the red dot indicator(s) in the project tree. (These are gone when selecting a different project and selecting the previous one again. But that change does not yet happen immediately when adding an end time to the current timeframe.)

* Render the "Stop timer" toolbar icon as disabled.

* Render the "Project → Stop timer" menu entry as disabled.

**Comment by jansorg** [comment]
This should be fixed by the next update.
