### ISSUE TITLE
Initialize the end time with the current time when editing in current timeframe

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#72]
The end time of the currently active timeframe is obviously unset, but it can be edited. When doing so, the value is initialized as "01.01.2000 00:00". Since that is before a typical timeframe's start time, confirming such a value (by mistake of course) will result in a huge negative duration of ≥19 years.

It seems more intuitive to use the current datetime value as initial value in such a case.

**Comment by jansorg** [comment]
Best would be to not set any end time in the dialog when there's none specified. But that's not easily possible with Qt, therefore it's now set to the current time.
Fixed for the next update
