### ISSUE TITLE
Project report time range entry is messed up

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#73]
When configuring a project report with "Time entries → Filter by date" checked, the values entered for "Start" and "End" should be taken over into the "Time range" values listed at the top of the report. Also, the time range should be inclusive of both the "Start" and "End" days. So to create a range of just one day, one would set "Start" and "End" to the same date.

Currently, the "End" date is excluded from the calculated time range, and the whole time range is off by minus one day from the values entered.

Examples of values entered and the resulting time range shown on the report:

* "Start: 10.03.19, End: 20.03.19" → "Time range: 3/9/19 - 3/19/19"
* "Start: 22.03.19, End: 23.03.19" → "Time range: 3/21/19"
* "Start: 22.03.19, End: 22.03.19" → "Time range: 3/21/19 - 3/21/19" (no idea how that is calculated …)

**Comment by jansorg** [comment]
Should be fixed for the next update.
