### ISSUE TITLE
Don't show lines for dropping projects to other positions

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#76]
Project item ordering in the project tree is done automatically by alphanumeric sort order. That conflicts (logically) with the horizontal lines that are shown when hovering an item over the project tree with drag&drop, indicating that one could drop them into that position. When trying, nothing happens of course. So better not show these horizontal lines?

**Comment by jansorg** [comment]
Technically not a quick fix. The next update will only allow to drop on items and not between items. Hopefully that's good enough :)
