### ISSUE TITLE
Make project tree sort order case insensitive

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#77]
Currently, the alphanumeric sort order of project items on one level of the project tree is case-sensitive, like this:

> * 123 project
> * A project
> * Z project
> * a project
> * z project

As one cannot necessarily remember if one named a project with s lowercase or uppercase letter at its start, that's a bit cumbersome / confusing. Case-insensitive seems more intuitive:

> * 123 project
> * A project
> * a project
> * Z project
> * z project

**Comment by jansorg** [comment]
Fixed for next update.
