### ISSUE TITLE
After deleting one time entry, select the next one

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#79]
When wanting to delete multiple time entries using the keyboard, there are two typical uses:

1. Selecting all applicable time entries with <kbd>Shift</kbd> + arrow keys (or <kbd>Ctrl</kbd> + arrow keys to navigate and then <kbd>Ctrl</kbd> + <kbd>Space</kbd> to add one to the selection). Finally pressing <kbd>Del</kbd> to delete the selected entries.

2. Selecting a single time entry with just the arrow keys, pressing <kbd>Del</kbd> to delete it, and repeating that process.

For the second usage, it would be better if after deleting one time entry, a new one would be selected automatically (showing with dark blue background, not just the light blue single-cell background like now that indicates the keyboard focus). Because then, one can press <kbd>Del</kbd> again right away. It would allow to delete a group of time entries by simply pressing <kbd>Del</kbd> multiple times in a row.

**Comment by jansorg** [comment]
Fixed for the next update
