### ISSUE TITLE
Fix the duration value in the panel icon's tooltip window

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#82]
When mousing over the panel icon of the `tom-ui` panel icon, a small black tooltip window will appear after a second. When a task is active, it will show its name and current duration.

However, the duration shown here changes only every thirty seconds (tried by repeatedly mousing over the toolbar icon to see a new tooltip window). Due to this, the time value is not really exact.

Ideally, the tooltip window's content would be re-generated with the current duration value right before showing it. Alternatively as a quick but slightly incomplete fix, the duration could be shown with minute precision here only.

**Comment by jansorg** [comment]
The next update tries to fix this on X11/Linux. That's the only platform where Qt5 supports this kind of update. But I was unable to make this happen on Linux.
Polling tom in shorter intervals is possible, but I'd like to avoid unneeded updates.
