### ISSUE TITLE
Do not go into edit mode when clicking on a time entry of a multi-selection 

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#83]
The current behavior can be reproduced as follows:

1. Select multiple time entries, for example by pressing <kbd>Ctrl</kbd> + <kbd>A</kbd> in the time entry list.

2. Make a single left click on one of the selected time entries, in a column that is editable.

3. Now, only the time entry you clicked on will be selected, but also, the field of that time entry on which you clicked will be switched to edit mode.

The expected behavior is (I think) that only the selection should change to "just the entry on which I clicked", without going into edit mode just yet. Because in such a case, the user most probably made the click to get out of multi-selection mode, not to edit anything. So to edit, the user would have to click again on the editable column of the selected time entry.

**Comment by jansorg** [comment]
Should be fixed for the next update
