### ISSUE TITLE
Sum up selected time entries in the footer bar

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#84]
This is a feature proposal, and I'm not that sure it is a great idea … but I hope so :-)

Some people who use the "Notes" column of time entries to enter information about exactly what sub-task was done. For them, it would be relevant to be able to quickly sum up several time entries with work on the same or related sub-tasks. This can be needed for ones own overview or to add the sums into some kind of report or spreadsheet. This proposed feature would be quite flexible, as when selecting "All projects" in the project tree first, one would be able to sum up any subset of _all_ time entries.

The simplest implementation would probably be to show the sum of all selected time entries in a footer bar. That's a mechanism people know from spreadsheets already.

**Comment by jansorg** [comment]
Done for the next update
