### ISSUE TITLE
Fix that dropping time entries on the ≥2nd column in the project tree assigns it to the parent project

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#85]
When drag & dropping a time entry to the first column ("Name") of the project tree, things work as expected (except for small issue #76).

When drag & dropping a time entry to any other column ("Today", "This week" etc.), dropping the item on a line will not assign it to the corresponding project but to the parent of that project. This seems to be because the only indicator for dropping time entries are lines in this case, never the frames indicating drag & drop into the framed project, unlike for the first column.

Instead, I guess the most consistent behavior would be to show frames in this case as well. And to show the frames always around all columns of the targeted project row, not just around a single row. Because ultimately, one assigns a time entry to a whole row, not to a part of it.

**Comment by jansorg** [comment]
Dropping will be possible for all columns in the project tree with the next update. Inserting between projects will be disabled.
