### ISSUE TITLE
Improve the "holding position" of time entries during drag & drop

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#86]
Currently, the position where one grabs a group of selected time entries for drag & drop is the position where one will "hold" them with the mouse pointer before finally dropping them. I did not notice this behavior at first and only wondered why the time entries always block me from seeing where I want to drop them :smile: Probably others will have the same issue, as different "holding positions" during drag & drop are quite a rare feature … I do not remember seeing this before.

I guess there are several ways how this could be improved:

* Setting the pointer to a constant "holding position" in the top left corner of the time entries during a drag & drop. That allows to easily see where to drop them.

* Not showing the time entries at all during drag & drop, instead just an icon symbolizing them. However, showing them is also useful because it assures the user that indeed all entries of a multi-selection will be drag & dropped.

**Comment by jansorg** [comment]
The next update will display a small icon instead. This could be improved in the future.
