### ISSUE TITLE
Reporting: Add a "Save as …" button

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#87]
Another user of `tom-ui`, who happens to be a brother of mine, did not find the way how to save a report ("right click on the report area, choose 'Save page'").

It would be more obvious to have a button "Save as …" in the bottom left of the window, next to "Update report".

The context menu when right-clicking on the report area can then be completely disabled, as none of the options are needed anymore ("View page source" would be useful, but does not work atm).

**Comment by jansorg** [comment]
@tanius Hm, the latest version is supposed to already have this, save as is available when you click the down arrow. Or press `Ctrl+S` to invoke this action.
![Screenshot_20190605_172214](https://user-images.githubusercontent.com/11473063/58968541-8237bf80-87b6-11e9-818e-8879c774bbb7.png)

**Comment by tanius** [comment]
Huh that's strange :-) I have `tom-ui` 0.8.0 installed and that screen portion looks like this:

![Screenshot ReportWindowButton](https://user-images.githubusercontent.com/843907/58969479-122a3900-87b8-11e9-8ce6-cecca30d89b8.png)

Also Ctrl + S does nothing in that window and the context menu still shows even though [you disabled it](https://github.com/jansorg/tom-ui/issues/46#issuecomment-482801199).

Maybe the relevant commits didn't make it into the release accidentally?

**Comment by jansorg** [comment]
Will be in the next update
