### ISSUE TITLE
Remove line breaks when pasting into the project name field

### ISSUE THREAD

**Issue by tanius** [jansorg/tom-ui#88]
When choosing "Create new subproject…" and then pasting a name that contains a line break (as it accidentally happens when copying from PDF), that line break will become part of the project name after confirming the dialog. But in such a way that only the part after that line break is shown in the project tree.

Replacing all line break characters with space characters would help. Anyway, this is quite an edge case …

**Comment by jansorg** [comment]
Should be fixed with the next update
