### ISSUE TITLE
Reporting: Missing time-entries

### ISSUE THREAD

**Issue by damingo** [jansorg/tom-ui#91]
When one creates monthly reports and e.g. a time-entry starts at 2019-02-28 23:00pm and ends 2019-03-01 0:50am the time entry is not included in the February report and also not included in the March report.

**Comment by jansorg** [comment]
The main window status adds the relevant parts to each day and february, i.e. 1 hour to day 1 and 50 minutes to day 2 and march. I'll do the same for the reporting.
