### ISSUE TITLE
It is possible to move a project above "All projects"

### ISSUE THREAD

**Issue by damingo** [jansorg/tom-ui#93]
This shall not be possible. After a project is moved above "All projects" Tom-UI crashes.

**Comment by jansorg** [comment]
@damingo Hm, I can't reproduce that. Is there a way to reproduce?

**Comment by damingo** [comment]
When I drag a project to the very top left a line appears where it would be dropped - so it would be one level above "All projects". When you change it the arrow for all projects can also be removed as it makes no sense that "All projects" can be collapsed. Makes the tree look more flat which is good.

**Comment by jansorg** [comment]
Hopefully fixed for the next update, seems to be only possible on macOS.
